'use client'

import { useState } from 'react'
import { CyberCard } from '@/components/ui/cyber-card'
import { CyberButton } from '@/components/ui/cyber-button'
import { CyberInput } from '@/components/ui/cyber-input'
import { StatusDot } from '@/components/ui/status-dot'
import { FileText, Copy, CheckCheck } from 'lucide-react'
import Link from 'next/link'
import { toast } from 'sonner'

type DocType = 'proposal' | 'contract' | 'brief'

const TEMPLATES = [
  { id: 'contract' as DocType, label: 'Freelance Service Agreement', desc: 'Standard contract for project work' },
  { id: 'proposal' as DocType, label: 'Project Proposal', desc: 'Professional proposal template' },
  { id: 'brief' as DocType, label: 'Project Brief', desc: 'Clear project brief format' },
]

const UK_COMPLIANCE = [
  { item: 'HMRC Self Assessment registration', status: 'check' },
  { item: 'National Insurance contributions', status: 'check' },
  { item: 'IR35 awareness (if applicable)', status: 'warning' },
  { item: 'GDPR data processing compliance', status: 'check' },
]

export default function DocumentsPage() {
  const [docType, setDocType] = useState<DocType>('proposal')
  const [formData, setFormData] = useState({ client: '', project: '', budget: '', timeline: '', details: '' })
  const [generatedDoc, setGeneratedDoc] = useState('')
  const [loading, setLoading] = useState(false)
  const [copied, setCopied] = useState(false)

  async function handleGenerate() {
    setLoading(true)
    try {
      const res = await fetch('/api/rex/documents', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ type: docType, data: formData }),
      })
      const data = await res.json()
      if (!res.ok) throw new Error(data.error)
      setGeneratedDoc(data.document)
      toast.success('Document generated by REX')
    } catch {
      toast.error('Failed to generate document')
    } finally {
      setLoading(false)
    }
  }

  async function handleCopy() {
    await navigator.clipboard.writeText(generatedDoc)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <div className="flex flex-col gap-6">
      <div className="flex items-center justify-between">
        <div>
          <div className="flex items-center gap-3 mb-1">
            <span className="text-2xl">🗂️</span>
            <h1 className="font-orbitron text-xl text-text">REX — AI OPERATIONS MANAGER</h1>
            <StatusDot status="active" label />
          </div>
          <p className="text-textMuted font-rajdhani text-sm">Proposals, contracts, documents, and compliance</p>
        </div>
        <Link href="/agents/rex" className="border border-orange-400/40 text-orange-400 font-orbitron text-xs px-4 py-2 hover:bg-orange-400/5 transition-colors">
          CHAT WITH REX →
        </Link>
      </div>

      <CyberCard variant="cyan" title="DOCUMENT GENERATOR">
        <div className="flex gap-2 mb-4">
          {(['proposal', 'contract', 'brief'] as DocType[]).map(t => (
            <button key={t} onClick={() => setDocType(t)} className={`px-3 py-1.5 font-orbitron text-xs uppercase transition-colors ${docType === t ? 'bg-cyan text-background' : 'border border-border text-textMuted hover:border-cyan/40'}`}>
              {t}
            </button>
          ))}
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3 mb-4">
          <CyberInput label="Client Name" placeholder="Acme Corp" value={formData.client} onChange={e => setFormData(p => ({ ...p, client: e.target.value }))} />
          <CyberInput label="Project" placeholder="Brand redesign" value={formData.project} onChange={e => setFormData(p => ({ ...p, project: e.target.value }))} />
          <CyberInput label="Budget" placeholder="£5,000" value={formData.budget} onChange={e => setFormData(p => ({ ...p, budget: e.target.value }))} />
          <CyberInput label="Timeline" placeholder="6 weeks" value={formData.timeline} onChange={e => setFormData(p => ({ ...p, timeline: e.target.value }))} />
        </div>
        <div className="mb-4">
          <label className="text-cyan text-xs font-orbitron uppercase tracking-widest block mb-1">Additional Details</label>
          <textarea rows={3} className="w-full px-4 py-3 bg-surface border border-border text-text font-rajdhani text-sm outline-none focus:border-cyan resize-none" placeholder="Special requirements..." value={formData.details} onChange={e => setFormData(p => ({ ...p, details: e.target.value }))} />
        </div>
        <CyberButton onClick={handleGenerate} loading={loading}>
          <FileText size={14} /> GENERATE WITH REX
        </CyberButton>
      </CyberCard>

      {generatedDoc && (
        <CyberCard variant="ghost" title="GENERATED DOCUMENT">
          <div className="flex justify-end mb-3">
            <button onClick={handleCopy} className="flex items-center gap-1.5 text-xs font-orbitron text-textMuted hover:text-cyan transition-colors">
              {copied ? <><CheckCheck size={12} className="text-green" /> COPIED</> : <><Copy size={12} /> COPY</>}
            </button>
          </div>
          <pre className="text-text text-sm font-rajdhani leading-relaxed whitespace-pre-wrap">{generatedDoc}</pre>
        </CyberCard>
      )}

      <div>
        <h2 className="font-orbitron text-xs text-cyan uppercase tracking-widest mb-3">DOCUMENT TEMPLATES</h2>
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
          {TEMPLATES.map(t => (
            <div key={t.id} className="bg-surface border border-border p-4 hover:border-orange-400/30 transition-colors">
              <FileText size={18} className="text-orange-400 mb-2" />
              <p className="text-text text-sm font-rajdhani font-semibold mb-1">{t.label}</p>
              <p className="text-textMuted text-xs font-rajdhani mb-3">{t.desc}</p>
              <button onClick={() => { setDocType(t.id); setFormData(p => ({ ...p, project: t.label })) }} className="text-orange-400 text-xs font-orbitron hover:opacity-80 transition-opacity">
                USE TEMPLATE →
              </button>
            </div>
          ))}
        </div>
      </div>

      <CyberCard variant="ghost" title="COMPLIANCE CHECKLIST — UK">
        <div className="flex flex-col gap-3">
          {UK_COMPLIANCE.map(({ item, status }) => (
            <div key={item} className="flex items-center gap-3">
              <span className={status === 'check' ? 'text-green text-sm' : 'text-yellow text-sm'}>{status === 'check' ? '✓' : '⚠'}</span>
              <span className="text-text text-sm font-rajdhani">{item}</span>
            </div>
          ))}
        </div>
        <p className="text-textMuted text-xs font-rajdhani mt-4">Chat with REX for detailed guidance on any compliance item.</p>
      </CyberCard>
    </div>
  )
}
